### ISSUE TITLE
Question about scoring and colocation

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry-incubator/auction#4]
Hello,

This is maybe a stupid but in the scoring function

```go
func (c *Cell) computeScore(remainingResources auctiontypes.Resources, numInstances int) float64 {
	fractionUsedMemory := 1.0 - float64(remainingResources.MemoryMB)/float64(c.state.TotalResources.MemoryMB)
	fractionUsedDisk := 1.0 - float64(remainingResources.DiskMB)/float64(c.state.TotalResources.DiskMB)
	fractionUsedContainers := 1.0 - float64(remainingResources.Containers)/float64(c.state.TotalResources.Containers)

	resourceScore := (fractionUsedMemory + fractionUsedDisk + fractionUsedContainers) / 3.0
	resourceScore += float64(numInstances)

	return resourceScore
}
```

Why do we add  ```resourceScore += float64(numInstances)```  instead of removing score ?
I mean if I want to distribute my application instance maybe I prefer to choose where I don't have other / less same instance of my application If I lost a cell the impact should be less for my application.

Again maybe I am missing something...

Thanks.

**Comment by ematpl** [comment]
Hi, @shinji62,

The scores for the cells are calculated such that a score closer to 0 indicates a better fit for the LRP instance or Task being auctioned. With the addition of the existing instance count to the score, the more instances already on that cell, the higher that cell's score will be, and the worse the fit. Since the memory/disk/container count score is always less than or equal to 1, and the instance counts are integers, any positive instance count already on a cell will be considered more heavily than a better resource match. Consequently, this scoring function places a high value on distributing app instances evenly across compatible cells instead of letting them accumulate on a single cell.

Thanks,
Eric

**Comment by Amit-PivotalLabs** [comment]
It's an auction where the lowest score wins.

**Comment by shinji62** [comment]
Thanks Guy, now everything make sens :)

**Comment by ematpl** [comment]
Thanks, @shinji62, closing this out.
